# Build stage
FROM node:20.11.0 as build

WORKDIR /app

# Copy package.json, package-lock.json
COPY package*.json ./

RUN npm install

# Copy source code
COPY . .

# Build
RUN npm run build

# Serve ứng dụng đã build bằng Nginx
FROM nginx:alpine

# Copy 
COPY --from=build /app/dist /usr/share/nginx/html

# Expose
EXPOSE 80

# Run nginx
CMD ["nginx", "-g", "daemon off;"]
