version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /root/mongo-data

  server:
    container_name: card-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped

  # client:
  #   container_name: card-client
  #   build:
  #     context: ./client
  #     args:
  #       MODE: development
  #     dockerfile: Dockerfile 
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #   command: npm run dev  
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true  
  #     - CLIENT_URI_1=http://localhost:3000
  #     - SERVER_URI_2=http://localhost:8080

  #   restart: unless-stopped

  # client:
  #   container_name: card-client
  #   build:
  #     context: ./client
  #     args:
  #       MODE: production
  #     dockerfile: Dockerfile 
  #   ports:
  #     - "3000:80" 
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #     - ./client/.env.production:/app/.env
  #   environment:
  #     - NODE_ENV=production 
  #   command: npm run build  
  #   restart: unless-stopped

volumes:
  mongo-data:
