export const MY_NAME = 'Dai Nguyen';
export const COLOR_BLACK_1 = 'rgba(0,0,0,.25)';
export const MY_GITHUB = "https://github.com/dainv123"
export const LOGO_URI = '/public/images/logo2.png';
export const AVATAR_URI = '/public/assets/images/avatar.jpg';
export const ABOUT_ME_IMAGE = '/public/assets/images/about.png';
export const CONTACT_MAILBOX = '/public/assets/images/mailbox.png';
export const BLOG_1_IMAGE = '/public/assets/images/blog/350x467.png';
export const BLOG_2_IMAGE = '/public/assets/images/blog/728x305.png';
export const BLOG_3_IMAGE = '/public/assets/images/blog/350x234.png';
export const UPLOADS_FOLDER = 'uploads';