/*************************
 WORDINGS
*************************/
export const COPY_RIGHT = 'DAIDEV - developed by testofdai@gmail.com';
export const UPDATE_USER_SUCCESSFULLy = 'User updated successfully';
export const MAKE_YOUR_BLOG = 'Make Your Blog';
export const ADD_YOUR_BLOG = "Add Your Blog";
export const UPDATE_YOUR_BLOG = "Update Your Blog";
export const CANCEL = 'Cancel';
export const SUBMIT = 'Submit';
export const UNDO = 'Undo';
export const EDIT = 'Edit';
export const NAME = 'Name';
export const TREND = 'Trend';
export const INTRODUCTION = 'Introduction';
export const CONTENT = 'Content';
export const IMAGE = 'Image';
export const MAKE_YOUR_CARD = 'Make Your Card';
export const ADD_YOUR_CARD = "Add Your Card";
export const UPDATE_YOUR_CARD = "Update Your Card";
export const ADD_YOUR_IMAGE = "Add Your Image";
export const UPDATE_YOUR_IMAGE = "Update Your Image";
export const SELECT_THEME = 'Select Theme';
export const CONFIG = 'Config';
export const SETTING = 'Setting';
export const RESET_TO_DEFAULT = 'Reset to default';
export const AI_FORM = 'AI Form';
export const ENTER_REQUIREMENT = 'Enter your requirement';
export const EMAIL_SENT = 'Email Sent!';
export const UPLOAD = 'Upload';
export const LOG_IN = 'Log In';
export const DASHBOARD = 'Dashboard';
export const SIGN_OUT = 'Sign Out';
export const HOME = 'Home';
export const ABOUT_ME = 'About Me';
export const THEME = 'Theme';
export const BLOG = 'Blog';
export const CONTACT = 'Contact';
export const LOGGED_IN_SUCCESSFULLY = 'Logged in successfully';
export const INCORRECT_EMAIL_PASSWORD = 'Incorrect email or password.';
export const EMAIL = 'Email';
export const PASSWORD = 'Password';
export const FORGOT_PASSWORD = 'Forgot password';
export const REMEMBER_ME = 'Remember me';
export const OR = 'Or';
export const REGISTER_NOW = 'register now!';
export const EMAIL_HAS_ALREADY = 'Email has already been taken.';
export const USERNAME_HAS_ALREADY = 'Username has already been taken.';
export const REGISTER = 'Register';
export const USERNAME = 'Username';
export const CONFIRM_PASSWORD = "Confirm Password";
export const AGREE_LOGIN = 'I agree to FAKE Terms of Service';
export const ALREADY_HAVE_ACCOUNT = 'Already have an account?';
export const MAKE_YOUR_TAG = "Make Your Tag";
export const ADD_YOUR_TAG = "Add Your Tag";
export const UPDATE_YOUR_TAG = "Update Your Tag";
export const MAKE_YOUR_THEME = "Make Your Theme";
export const ADD_YOUR_THEME = "Add Your Theme";
export const UPDATE_YOUR_THEME = "Update Your Theme";
export const PATH = "Path";
export const SELECT_TAGS = "Select Tags";
export const GITHUB = "Github";
export const COPY_CLIPBOARD_OK = 'Text copied to clipboard';
export const COPY_CLIPBOARD_ERROR = 'Failed to copy text to clipboard';
export const ABOUT_ME_INTRO = "WHAT DO YOU WANT TO KNOW ABOUT ME?";
export const ABOUT_ME_ADDRESS = 'Ho Chi Minh City, Viet Nam';
export const ABOUT_ME_CONTENT_1 = "Hey there! I'm Nguyen Van Dai, a Developer calling Ho Chi Minh city home ☀️. I identify as a passionate developer, embracing the world of coding, open source, and the web platform ❤️.";
export const ABOUT_ME_CONTENT_2 = "Beyond my professional responsibilities, I actively engage in crafting and contributing to open source projects, a practice that not only broadens my knowledge but also aids in the advancement of fellow open source endeavors. Additionally, I take pleasure in sharing my technical insights ✍️ through my blog or";
export const ABOUT_ME_CONTENT_3 = "During my leisure hours, you'll likely find me backpacking, exploring mountains or beaches 🏖, or attending tech fairs in and around Ho Chi Minh city.";
export const BLOG_INTRO = "I share my news and blog";
export const CONTACT_INTRO = "NEED SOME HELP?";
export const MESSAGE = 'Message';
export const SEND_MESSAGE = 'Send Message';
export const WEB_DEVELOPER = 'Senior Web Developer';
export const MOBILE_DEVELOPER = 'Also, Mobile Developer';
export const BACKEND_DEVELOPER = 'Culi in Some Backend Languages';
export const AND = 'and';
export const CONTACT_ME = 'Contact Me';
export const GO_TO_ADMIN = 'Go to Admin';
export const PAGE_NOT_FOUND = '404 - Page Not Found';
export const USER_NAME = "User Name";
export const SAVE = 'Save';
export const PROFILE = 'Profile';
export const SOMETHING_WENT_WRONG = 'Something went wrong!';
export const SEND_CONTACT_SUCCESSFULLY = 'Your message has been successfully sent!';
export const THEME_INTRO = 'Feel free to take a brief look and utilize them as needed.';
export const ALL = 'All';
export const E_MAIL = 'E-mail';
export const PROJECT = 'Project';
export const VERIFY_USER_SUCCESSFULLY = 'Verify user account successfully';
export const IMAGES = 'IMAGE(S)';
export const ADD_IMAGE = 'ADD IMAGE';
export const CARDS = 'CARD(S)';
export const ADD_CARD = 'ADD CARD';
export const THEMES = 'THEME(S)';
export const ADD_THEME = 'ADD THEME';
export const TAGS = 'TAG(S)';
export const ADD_TAG = 'ADD TAG';
export const BLOGS = 'BLOG(S)';
export const ADD_BLOG = 'ADD BLOG';
/*************************
 MESSAGES
*************************/
export const ENTER_VALID_INFO_MESSAGE = `Please provide a valid email and password`;
export const ENTER_EMAIL_PASSWORD_MESSAGE = `Please enter your email and password.`;
export const MUST_BE_VALID_EMAIL_MESSAGE = 'Must be a valid email';
export const MUST_ACCEPT_TERM_MESSAGE = 'Must Accept Terms and Conditions';
export const MUST_AT_LEAST_ONE_MESSAGE = 'Must have at least one letter and one digit.';
export const ONLY_NUMBER_LETTER_MESSAGE = 'Must only contain letters and numbers';
export const PASSWORD_MUST_MATCH_MESSAGE = 'Passwords must match';
export const PASSWORD_CONFIRMATION_MESSAGE = 'Password confirmation';
export const REQUIRE_PROCESSING_MESSAGE = "This field is required for AI processing";
export const REQUIRE_REQUIREMENT_MESSAGE = 'Please enter your requirement!';
/*************************
 CALLER
*************************/
export const HELLO_NAME = name => `Hello, I'm ${name}`;
export const MIN_MESSAGE = min => `Must have at least ${min} characters`;
export const MAX_MESSAGE = max => `Cannot have more than ${max} characters`;
export const REQUIRED_MESSAGE = field => `${field} is required`;
export const CHECK_EMAIL_PLEASE = email => `Email sent to ${email}! Check your email and verify your account.`;
export const FILE_UPLOAD_FAILED = filename => `${filename} file upload failed.`;
export const MAXIMUM_UPLOAD_MESSAGE = maxCount => `Maximum ${maxCount} images allowed.`;